# I sogni delle macchine - Una visione diametrale #

Un fatto molto affascinante legato al lavoro dell’EHT sta proprio nel metodo in cui “la fotografia del secolo” è stata realizzata. Il buco nero che è stato osservato è un corpo celeste “estremamente piccolo” in confronto alla distanza di 55 milioni di anni luce che ci separa da esso, e la sua osservazione avrebbe richiesto un telescopio dotato di una lente grande quanto la circonferenza del pianeta terra.

La cosa affascinante è che un telescopio con una lente così grande è stato effettivamente realizzato: 8 telescopi situati alle Hawaii, in Messico, in Arizona, in Spagna, in Cile e in Antartide sono stati collegati in rete tra loro per essere puntati, con precisione assoluta, verso lo stesso punto dello spazio profondo. 700 TeraByte di dati provenienti da tutte le stazioni sono interpolate tra loro per realizzare un’unica immagine, simulando quindi una fotografia scattata con una lente impossibile.

Questo tipo di operazioni è la specialità delle IA che sfruttano il machine learning. Sistemi come deep dream sono in grado di riconoscere potenziali pattern all’interno di qualunque immagine, interpretando i dettagli come cose che “ha già visto” in un database, mentre diversamente i sistemi di style transfer sono in grado di analizzare due file e di realizzare, con varie gradazioni intermedie che possono essere più vicine alla prima piuttosto che alla seconda, nuovi file interpretati che hanno punti in comune tra entrambe le immagini, interpretando i dettagli di uno come morphing dei dettagli dell’altro.

Così come è stata compiuta questa impresa, è possibile osservare quello che succede sulla terra sfruttando occhi o orecchie situati a grande distanza nello spazio o nel tempo? Sfruttando la capacità del machine learning di immaginare “le vie di mezzo” tra due oggetti, è possibile punti di vista diversissimi e persone con storie diverse tra loro per realizzare un’unica visione dei fatti e delle cose del mondo?
